title: zigzagjie的中文博客小站
author: Jie Lou
email: jlou1@andrew.cmu.edu
description: > # this means to ignore newlines until "baseurl:"
  记录生活的点滴

# social links
#twitter_username: jekyllrb
github_username:  zigzagjie
#rss: rss
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: Jie Lou
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
exclude:
  - Gemfile
  - Gemfile.lock



# basic options
#title: Jie Lou's Data Amusement Park
#author: Jie Lou
#email: jlou1@andrew.cmu.edu
#description: This website is to showcase some data science projects
#twitter_username: zigzagjie
#github_username:  zigzagjie

# Build settings
#markdown: kramdown
#theme: minima




#theme: jekyll-theme-minimal
