# basic options
title: Jie Lou's Data Amusement Park
author: Jie Lou
email: jlou1@andrew.cmu.edu
description: This website is to showcase some data science projects
twitter_username: zigzagjie
github_username:  zigzagjie

# Build settings
markdown: kramdown
theme: minima




#theme: jekyll-theme-minimal
